const FETCH_ALL = "FETCH_ALL";
const FETCH_BY_SEARCH = "FETCH_BY_SEARCH";
const CREATE = "CREATE";
const DELETE = "DELETE";
const UPDATE = "UPDATE";
const AUTH = "AUTH";
const LOGOUT = "LOGOUT";
const START_LOADING = "START_LOADING";
const END_LOADING = "END_LOADING";
const FETCH_POST = "FETCH_POST";
const POST_COMMENT = "POST_COMMENT";

export {
  FETCH_ALL,
  CREATE,
  DELETE,
  UPDATE,
  AUTH,
  LOGOUT,
  FETCH_BY_SEARCH,
  START_LOADING,
  END_LOADING,
  FETCH_POST,
  POST_COMMENT,
};
